"""Validate framework assessments and derive accessible report tables."""

import hashlib
import html
import json
import re
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter

from ._coverage import coverage_summary


class CheckAssessment(BaseModel):
    """A framework judgment with optional question-level counts."""

    model_config = ConfigDict(extra="forbid")
    id: str
    assessment: Literal["None", "Minor", "Major", "Critical", "Not assessed", "Not applicable"]
    result: str = Field(min_length=1)
    evidence: list[str]
    checked_ids: list[str] | None = None
    affected_ids: list[str] | None = None


def framework_definitions(report: Path) -> dict[str, dict[str, str]]:
    """Read names AND meanings from the pinned GL registry without a second taxonomy."""
    source = (report / "framework/auditframework.sty").read_text()
    source = re.sub(r"(?m)^\s*%.*$", "", source)
    source = source.replace("%\n", "\n")
    letters = dict(re.findall(r"\\dimensionletter\{([^}]+)\}\{([^}]+)\}", source))
    checks: dict[str, dict[str, str]] = {}
    for block in re.split(r"\\definedimension\{", source)[1:]:
        match = re.match(r"([^}]+)\}\{([^}]+)\}\{([^}]+)\}\{([^}]+)\}", block)
        if match is None or match[1] not in letters:
            continue
        letter = letters[match[1]]
        checks[letter] = dict(name=match[2], definition=" ".join(match[4].split()), dimension=match[1])
        for index, (name, meaning) in enumerate(re.findall(r"\\gsub\{([^}]+)\}\{([^}]+)\}", block), 1):
            checks[f"{letter}.{index}"] = dict(name=name.replace(r"\&", "&"),
                definition=" ".join(meaning.split()), dimension=match[1])
    if len([key for key in checks if "." not in key]) != 9:
        raise ValueError("Expected all nine dimensions in the pinned framework")
    return checks


def framework_checks(report: Path) -> dict[str, str]:
    """Names keyed by framework IDs, for existing assessment consumers."""
    return {key: value["name"] for key, value in framework_definitions(report).items()}


def prepare_assessments(report: Path) -> None:
    """Stage a checklist and schema for a new investigation."""
    (report / "framework/checks.json").write_text(json.dumps(framework_definitions(report), indent=2))
    (report / "assessments.schema.json").write_text(json.dumps(TypeAdapter(list[CheckAssessment]).json_schema(), indent=2))
    (report / "assessments.json").write_text("[]\n")
    (report / "assessments.tex").write_text("% Generated by check_report.\n")


def assessment_tables(report: Path) -> str:
    """Validate complete assessments and coverage totals; return tables from those records."""
    checks = framework_checks(report)
    rows = TypeAdapter(list[CheckAssessment]).validate_json((report / "assessments.json").read_text())
    ids = [row.id for row in rows]
    if len(ids) != len(set(ids)) or set(ids) != set(checks):
        raise ValueError("assessments.json must contain every framework dimension and check exactly once")
    coverage = None
    if (report / "coverage.json").exists():
        recorded = json.loads((report / "coverage.json").read_text())
        coverage = coverage_summary([r["question_id"] for r in recorded["questions"]],
                                    [a for r in recorded["questions"] for a in r["assessments"]])
        if recorded != coverage:
            raise ValueError("coverage.json must match export_coverage results; resolve source assessments before exporting")
    population = {r["question_id"] for r in coverage["questions"]} if coverage else None
    for row in rows:
        if not row.result.strip() or any(not ref.strip() for ref in row.evidence):
            raise ValueError(f"{row.id}: empty result or evidence")
        if row.assessment not in ("Not assessed", "Not applicable") and not row.evidence:
            raise ValueError(f"{row.id}: completed assessments require evidence")
        if (row.checked_ids is None) != (row.affected_ids is None):
            raise ValueError(f"{row.id}: provide both checked_ids and affected_ids or neither")
        if row.checked_ids is not None and row.affected_ids is not None:
            if population is None:
                raise ValueError(f"{row.id}: question counts require report/coverage.json")
            if len(set(row.checked_ids)) != len(row.checked_ids) or len(set(row.affected_ids)) != len(row.affected_ids):
                raise ValueError(f"{row.id}: duplicate question IDs")
            if row.assessment == "None" and row.affected_ids:
                raise ValueError(f"{row.id}: a clean assessment cannot list affected questions")
            if not set(row.affected_ids) <= set(row.checked_ids) <= population:
                raise ValueError(f"{row.id}: affected IDs must be checked and in the population")
    esc = html.escape
    parts = []
    if coverage:
        parts.append('<h3>Questions assessed</h3><table><tr><th>Status</th><th>Questions</th><th>Percent</th></tr>')
        for status, count in coverage["counts"].items():
            parts.append(f'<tr><td>{esc(status.replace("_", " ").capitalize())}</td><td>{count}/{coverage["denominator"]}</td><td>{coverage["percentages"][status]:.1f}%</td></tr>')
        parts.append('</table><h3>Defect types</h3><p>Counts are unique questions per type; types may overlap. These are not counts of misgraded submissions.</p><table><tr><th>Type</th><th>Questions</th></tr>')
        for kind, count in coverage["defect_counts"].items():
            parts.append(f'<tr><td>{esc(kind.replace("_", " "))}</td><td>{count}/{coverage["denominator"]}</td></tr>')
        parts.append(f'<tr><td>Unclassified defects</td><td>{coverage["unclassified_defects"]}</td></tr></table>')
    by_id = {row.id: row for row in rows}
    for dimensions in (True, False):
        parts.append('<h3>Scorecard</h3>' if dimensions else '<details><summary>Full check assessments</summary>')
        parts.append('<table><tr><th>Check</th><th>Assessment</th><th>Affected / checked</th><th>Result</th><th>Evidence</th></tr>')
        for key, name in checks.items():
            if ('.' not in key) != dimensions:
                continue
            row = by_id[key]
            count = f"{len(row.affected_ids or [])}/{len(row.checked_ids)}" if row.checked_ids is not None else "—"
            badge = row.assessment.lower().replace(' ', '-')
            parts.append(f'<tr><td>{esc(name)}</td><td><span class="assessment {badge}">{esc(row.assessment)}</span></td><td>{count}</td><td>{esc(row.result)}</td><td>{esc("; ".join(row.evidence))}</td></tr>')
        parts.append('</table>' if dimensions else '</table></details>')
    if coverage:
        parts.append('<details><summary>Question-level results</summary><table><tr><th>Question</th><th>Status</th><th>Defect types</th><th>Explanation</th><th>Evidence</th><th>Next check</th></tr>')
        for question in coverage["questions"]:
            assessments = question["assessments"]
            kinds = sorted({kind for a in assessments for kind in a["defect_types"]})
            explanations = " ".join(a["explanation"] for a in assessments)
            evidence = "; ".join(dict.fromkeys(ref for a in assessments for ref in a["evidence"]))
            next_checks = " ".join(a["next_check"] for a in assessments if a["next_check"])
            parts.append(f'<tr><td>{esc(question["question_id"])}</td><td>{esc(question["status"])}</td><td>{esc(", ".join(kinds))}</td><td>{esc(explanations)}</td><td>{esc(evidence)}</td><td>{esc(next_checks)}</td></tr>')
        parts.append('</table></details>')
    return '\n'.join(parts)


def latex_escape(text: str) -> str:
    """Escape literal assessment text, never interpret it as executable TeX."""
    replacements = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
                    "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
                    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(replacements.get(char, char) for char in text)


def assessment_latex(report: Path) -> str:
    """Generate GL dimension summaries and contribution rows from validated records."""
    assessment_tables(report)  # Shared validation of population, counts and records.
    definitions = framework_definitions(report)
    rows = TypeAdapter(list[CheckAssessment]).validate_json((report / "assessments.json").read_text())
    by_id = {row.id: row for row in rows}
    macros = {"None": "assessNone", "Minor": "assessMinor", "Major": "assessMajor",
              "Critical": "assessCritical", "Not assessed": "assessNotAssessed", "Not applicable": "assessNA"}
    parts = ["% Generated from assessments.json; edit the records, not this file."]
    for letter in sorted(key for key in definitions if "." not in key):
        row = by_id[letter]
        parts.append(r"\setdimension{" + definitions[letter]["dimension"] + "}{\\" + macros[row.assessment] + "}{}")
        parts.append(r"\newcommand{\summary" + letter + "}{" + latex_escape(row.result) + "}")
        parts.append(r"\newcommand{\checks" + letter + "}{%")
        for key, definition in definitions.items():
            if not key.startswith(letter + "."):
                continue
            check = by_id[key]
            count = (f" {len(check.affected_ids or [])}/{len(check.checked_ids)} assessed questions affected."
                     if check.checked_ids is not None else "")
            parts.append(r"\contributionrow{" + key + "}{" + latex_escape(definition["name"]) +
                         "}{\\" + macros[check.assessment] + "}{" + latex_escape(check.result + count) + "}")
        parts.append("}")
    return "\n".join(parts) + "\n"


def validate_latex_structure(report: Path, findings: list[tuple[str, str]]) -> None:
    """Require the fixed dimension layout and a narrative home for supported findings."""
    template = Path(__file__).parent / "investigation/report"
    if (report / "report.tex").read_bytes() != (template / "report.tex").read_bytes():
        raise ValueError("Keep the supplied Audit Findings wrapper unchanged; edit Findings.tex and metadata.tex")
    provenance = json.loads((template / "framework/provenance.json").read_text())
    for name, entry in provenance["files"].items():
        if hashlib.sha256((report / "framework" / name).read_bytes()).hexdigest() != entry["sha256"]:
            raise ValueError(f"Pinned framework file changed: {name}")
    source = (report / "Findings.tex").read_text()
    source = re.sub(r"(?m)(?<!\\)%.*$", "", source)
    definitions = framework_definitions(report)
    expected = [definitions[key]["dimension"] for key in sorted(definitions) if "." not in key]
    blocks = re.findall(r"\\begin\{dimensionreview\}\{([^}]+)\}(.*?)\\end\{dimensionreview\}", source, re.S)
    if [key for key, _ in blocks] != expected:
        raise ValueError("Findings.tex must contain all nine GL dimensions exactly once in A-I order")
    for letter, (key, body) in zip("ABCDEFGHI", blocks, strict=True):
        overview = r"\dimensionoverview{" + key + r"}{\summary" + letter + r"}{\checks" + letter + "}"
        if overview not in body:
            raise ValueError(f"{key}: retain the generated dimension overview and check table")
        for finding_id, section in findings:
            if section == key and (r"\label{finding:" + finding_id + "}") not in body:
                raise ValueError(f"{finding_id}: explain this finding in the {key} dimension and add its finding label")
    for filename in ("Findings.tex", "metadata.tex"):
        if re.search(r"\bTODO\b|\bPLACEHOLDER\b|\[assessment\]|\[commit\]", (report / filename).read_text()):
            raise ValueError(f"Unfilled placeholder in {filename}")
