"""The audit sandbox: the audited task's own environment, reproduced.

An auditor needs to read (and sometimes run) the benchmark's real grading code, and
that code routinely lives outside the task's own package. Copying source is fragile
— the import graph fans straight into `inspect_ai` with no clean stopping point — so
the sandbox instead *installs* the distributions that provide the task, pinned to the
versions in the environment the audit is resolved in.
"""

import tempfile
from importlib.metadata import PackageNotFoundError, packages_distributions, version
from pathlib import Path

from inspect_ai import Task
from inspect_ai.util._sandbox.environment import SandboxEnvironmentType

__all__ = ["audit_sandbox", "task_requirements"]

DOCKERFILE = """\
# Generated by inspect_audit. The audited task's packages are installed so the
# auditor can read and run the real grading code in place.
FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\
        git jq ripgrep \\
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir {requirements}

WORKDIR /audit
CMD ["sleep", "infinity"]
"""


def _top_level_modules(task: Task) -> set[str]:
    """Top-level modules implicated in this task: its registry package and scorers."""
    modules: set[str] = set()

    # `inspect_evals/simpleqa_verified` -> `inspect_evals`
    if "/" in task.name:
        modules.add(task.name.split("/")[0])

    scorers = task.scorer if isinstance(task.scorer, list) else [task.scorer]
    for scorer in scorers:
        if scorer is None:
            continue
        fn = getattr(scorer, "__wrapped__", scorer)
        module = getattr(fn, "__module__", "")
        if module:
            modules.add(module.split(".")[0])

    return {m for m in modules if m and m.isidentifier()}


def task_requirements(task: Task) -> list[str]:
    """Pinned pip requirements that provide the audited task.

    Derived from the environment the audit is resolved in, which is the environment
    that could resolve the task in the first place — so it is the closest available
    description of what produced the logs.
    """
    pins: dict[str, str] = {}

    def pin(dist: str) -> None:
        try:
            pins[dist] = version(dist)
        except PackageNotFoundError:
            pass

    pin("inspect-ai")
    distributions = packages_distributions()
    for module in _top_level_modules(task):
        for dist in distributions.get(module, []):
            pin(dist)

    return [f"{dist}=={ver}" for dist, ver in sorted(pins.items())]


def audit_sandbox(task: Task) -> SandboxEnvironmentType:
    """A sandbox for auditing `task`, with the task's own packages installed.

    Writes a generated Dockerfile to a temporary directory and returns a sandbox
    spec pointing at it. Docker layer-caches the build, so the cost is paid once
    per distinct requirement set rather than per audit.
    """
    requirements = task_requirements(task)
    dockerfile = DOCKERFILE.format(requirements=" ".join(requirements))

    out = Path(tempfile.mkdtemp(prefix="inspect_audit_sandbox_")) / "Dockerfile"
    out.write_text(dockerfile)
    return ("docker", str(out))
