import atexit
import os
import re
import shutil
import tempfile
from importlib.metadata import PackageNotFoundError, packages_distributions, version
from logging import getLogger
from pathlib import Path
from typing import Any

import yaml
from inspect_ai import Task
from inspect_ai._eval.task.util import task_run_dir
from inspect_ai.dataset import Sample
from inspect_ai.util import SandboxEnvironmentSpec, SandboxEnvironmentType
from inspect_ai.util import sandbox as sandbox_env
from inspect_ai.util._sandbox.compose import is_dockerfile
from inspect_ai.util._sandbox.environment import resolve_sandbox_environment

logger = getLogger(__name__)

BENCHMARK_SERVICE = "benchmark"


async def run_benchmark_setup(script: str | None) -> None:
    """Run the audited sample's setup in the benchmark service.

    The setup is what populates a benchmark's per-sample state; benchmarks whose
    state is baked into a per-sample image (e.g. SWE-bench) carry no setup.
    """
    if not script:
        return
    result = await sandbox_env(BENCHMARK_SERVICE).exec(
        ["bash", "-c", script], timeout=300
    )
    if not result.success:
        raise RuntimeError(f"Benchmark setup failed: {result.stderr[:500]}")


# undo tracked edits and drop untracked files (but keep ignored build artifacts)
# in every git worktree in the box -- how an image-baked repo returns to pristine
_GIT_RESTORE = (
    'for g in $(find / -maxdepth 5 -type d -name .git 2>/dev/null); do '
    'r=$(dirname "$g"); git -C "$r" checkout -- . 2>/dev/null; '
    'git -C "$r" clean -fdq 2>/dev/null; done; true'
)


async def restore_benchmark(script: str | None) -> None:
    """Restore the benchmark service to its pristine per-sample state.

    Re-runs any setup, then reverts every git worktree in the box -- so a
    benchmark whose state comes from setup and one whose state is a checked-out
    repo both return to where the evaluated agent started.
    """
    await run_benchmark_setup(script)
    await sandbox_env(BENCHMARK_SERVICE).exec(
        ["bash", "-c", _GIT_RESTORE], timeout=300
    )

AUDITOR_NETWORK = "inspect_audit"

DOCKERFILE = """\
# Generated by inspect_audit. The audited task's packages are installed so the
# auditor can read and run the real grading code in place.
FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\
        ca-certificates curl git jq ripgrep \\
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir {requirements}

WORKDIR /audit
CMD ["sleep", "infinity"]
"""

# our own compose rather than inspect's auto-generated one, which sets
# `network_mode: none` -- an auditor without egress either reports it cannot
# verify or invents citations, and both have been observed
COMPOSE = """\
# Generated by inspect_audit.
services:
  default:
    build:
      context: "."
      dockerfile: "Dockerfile"
    command: "sleep infinity"
    init: true
    stop_grace_period: 1s
"""

AUDITOR_SERVICE: dict[str, Any] = {
    "build": {"context": None, "dockerfile": "Dockerfile"},
    "command": "sleep infinity",
    "init": True,
    # an `x-default` on any service beats one merely named `default`, so the
    # auditor must claim it or a benchmark declaring its own would receive the
    # audit's files, sliced logs and answers included
    "x-default": True,
    # our own network: a live host running curl and a full python was not next to
    # the benchmark container during the eval, so it must not be during the audit
    "networks": [AUDITOR_NETWORK],
    "stop_grace_period": "1s",
}


def task_requirements(task: Task) -> list[str]:
    """Pinned pip requirements that provide the audited task."""
    # the task's registry package plus each scorer's package
    modules: set[str] = set()
    if "/" in task.name:
        modules.add(task.name.split("/")[0])
    scorers = task.scorer if isinstance(task.scorer, list) else [task.scorer]
    for scorer in scorers:
        if scorer is None:
            continue
        fn = getattr(scorer, "__wrapped__", scorer)
        module = getattr(fn, "__module__", "")
        if module:
            modules.add(module.split(".")[0])
    modules = {m for m in modules if m and m.isidentifier()}

    # pin to the versions in the environment the audit resolved the task in
    pins: dict[str, str] = {}

    def pin(dist: str) -> None:
        try:
            pins[dist] = version(dist)
        except PackageNotFoundError:
            pass

    pin("inspect-ai")
    distributions = packages_distributions()
    for module in modules:
        for dist in distributions.get(module, []):
            pin(dist)

    return [f"{dist}=={ver}" for dist, ver in sorted(pins.items())]


def audit_sandbox(task: Task) -> SandboxEnvironmentType:
    """A sandbox for auditing `task`, with the task's own packages installed."""
    out = Path(tempfile.mkdtemp(prefix="inspect_audit_sandbox_"))
    if not os.environ.get("INSPECT_AUDIT_KEEP_STAGING"):
        atexit.register(shutil.rmtree, out, ignore_errors=True)
    (out / "Dockerfile").write_text(
        DOCKERFILE.format(requirements=" ".join(task_requirements(task)))
    )
    compose = out / "compose.yaml"
    compose.write_text(COMPOSE)
    return ("docker", str(compose))


def has_benchmark(spec: SandboxEnvironmentSpec | None) -> bool:
    """Whether the audited task's environment runs as a benchmark service."""
    config = spec.config if spec is not None else None
    return (
        isinstance(config, str)
        and not is_dockerfile(Path(config).name)
        and Path(config).is_file()
    )


def sample_sandbox(task: Task, sample: Sample) -> SandboxEnvironmentSpec | None:
    """The sandbox an audited sample actually runs in (its own, else its task's)."""
    return resolve_sandbox(task, sample.sandbox) or resolve_sandbox(task)


def resolve_sandbox(
    task: Task, sandbox: SandboxEnvironmentType | None = None
) -> SandboxEnvironmentSpec | None:
    """The audited task's own sandbox, with any relative config path made absolute."""
    spec = resolve_sandbox_environment(sandbox if sandbox is not None else task.sandbox)
    if spec is None:
        return None
    # inspect resolves relative config paths against the running task's directory,
    # which is the audit's, not the audited task's
    if isinstance(spec.config, str) and not Path(spec.config).is_absolute():
        return SandboxEnvironmentSpec(
            spec.type, (Path(task_run_dir(task)) / spec.config).as_posix()
        )
    return spec


def audit_compose(
    task: Task, spec: SandboxEnvironmentSpec | None, *, stage: Path
) -> SandboxEnvironmentType:
    """A sandbox holding the audited task's environment and the auditor's, side by side.

    The audited task's services are preserved as declared, except that a service
    named `default` is renamed: inspect treats that name as an alias for the default
    environment rather than a service lookup, so it would be unaddressable.

    Args:
        task: The task being audited.
        spec: The sandbox the audited sample runs in, or `None`.
        stage: Directory to write the merged compose and the auditor's Dockerfile into.
    """
    # no compose file to merge: the auditor's environment alone
    config = spec.config if spec is not None else None
    if not isinstance(config, str) or is_dockerfile(Path(config).name):
        return audit_sandbox(task)
    source = Path(config)
    if not source.is_file():
        return audit_sandbox(task)

    merged: dict[str, Any] = yaml.safe_load(source.read_text()) or {}
    services: dict[str, Any] = merged.get("services") or {}
    base = source.parent

    # rename their `default`, avoiding collisions with their other services
    benchmark_name = BENCHMARK_SERVICE
    while benchmark_name in services and benchmark_name != "default":
        benchmark_name += "_"

    # re-anchor relative paths and strip any x-default claims
    renamed = {}
    for name, service in services.items():
        anchored = _anchor_service(service, base)
        anchored.pop("x-default", None)
        renamed[benchmark_name if name == "default" else name] = anchored

    # rewrite depends_on references to the renamed service
    for service in renamed.values():
        depends = service.get("depends_on")
        if isinstance(depends, list):
            service["depends_on"] = [benchmark_name if d == "default" else d for d in depends]
        elif isinstance(depends, dict):
            service["depends_on"] = {
                (benchmark_name if k == "default" else k): v for k, v in depends.items()
            }

    # add the auditor service and its network
    stage.mkdir(parents=True, exist_ok=True)
    (stage / "Dockerfile").write_text(
        DOCKERFILE.format(requirements=" ".join(task_requirements(task)))
    )
    auditor = dict(AUDITOR_SERVICE)
    auditor["build"] = {"context": str(stage), "dockerfile": "Dockerfile"}
    merged["services"] = {"default": auditor, **renamed}
    networks = dict(merged.get("networks") or {})
    networks[AUDITOR_NETWORK] = None
    merged["networks"] = networks

    out = stage / "compose.yaml"
    out.write_text(yaml.safe_dump(merged, sort_keys=False))
    return ("docker", str(out))


# paths inside a compose file are relative to that file's directory, and the
# merged file lives somewhere else

def _anchor(value: Any, base: Path) -> Any:
    if isinstance(value, str) and not value.startswith(("/", "$")) and ":" not in value:
        return str((base / value).resolve())
    return value


def _anchor_service(service: dict[str, Any], base: Path) -> dict[str, Any]:
    out = dict(service)
    build = out.get("build")
    if isinstance(build, str):
        out["build"] = _anchor(build, base)
    elif isinstance(build, dict):
        build = dict(build)
        if "context" in build:
            build["context"] = _anchor(build["context"], base)
        out["build"] = build
    for key in ("env_file", "dockerfile"):
        if isinstance(out.get(key), str):
            out[key] = _anchor(out[key], base)
        elif isinstance(out.get(key), list):
            out[key] = [_anchor(v, base) for v in out[key]]
    if isinstance(out.get("volumes"), list):
        out["volumes"] = [_anchor_volume(v, base) for v in out["volumes"]]
    return out


def _anchor_volume(volume: Any, base: Path) -> Any:
    # both bind-mount syntaxes: a missed relative source is created empty by docker
    # and the benchmark container silently loses the data mounted there
    if isinstance(volume, str) and volume.startswith("."):
        host, _, rest = volume.partition(":")
        return f"{_anchor(host, base)}:{rest}"
    if isinstance(volume, dict) and volume.get("type") == "bind":
        bound = dict(volume)
        bound["source"] = _anchor(bound.get("source"), base)
        return bound
    return volume


EGRESS_POLICY = """\
additionalResources:
  - |
    apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: {{ template "agentEnv.fullname" $ }}-default-internet-egress
    spec:
      endpointSelector:
        matchLabels:
          io.kubernetes.pod.namespace: {{ .Release.Namespace }}
          {{- include "agentEnv.selectorLabels" $ | nindent 6 }}
          inspect/service: default
      egress:
        - toEndpoints:
            - matchLabels:
                io.kubernetes.pod.namespace: kube-system
                k8s-app: kube-dns
            - matchLabels:
                io.kubernetes.pod.namespace: kube-system
                k8s-app: node-local-dns
          toPorts:
            - ports:
                - port: "53"
                  protocol: ANY
              rules:
                dns:
                  - matchPattern: "*"
        - toEntities:
            - world
"""

_DURATION = re.compile(r"^((?P<h>\d+)h)?((?P<m>\d+)m)?((?P<s>\d+)s)?$")
_MEMORY = re.compile(r"^(?P<value>\d+(?:\.\d+)?)(?P<unit>gb?|mb?|kb?|b)$", re.IGNORECASE)
_MEMORY_UNITS = {"b": "", "k": "Ki", "m": "Mi", "g": "Gi"}


def _as_list(value: str | list[str]) -> list[str]:
    return value.split() if isinstance(value, str) else value


def _seconds(value: Any) -> int | None:
    match = _DURATION.match(str(value))
    if match is None or not any(match.groups()):
        return None
    h, m, s = (int(match.group(g) or 0) for g in ("h", "m", "s"))
    return h * 3600 + m * 60 + s


def _quantity(value: Any) -> Any:
    # `512m` -> `512Mi`; unrecognised values pass through for the chart to reject.
    match = _MEMORY.match(str(value))
    if match is None:
        return value
    return f"{match.group('value')}{_MEMORY_UNITS[match.group('unit')[0].lower()]}"


def _env(value: dict[str, Any] | list[str]) -> list[dict[str, str]]:
    if isinstance(value, dict):
        return [{"name": k, "value": "" if v is None else str(v)} for k, v in value.items()]
    return [{"name": k, "value": v} for k, _, v in (item.partition("=") for item in value)]


def _readiness_probe(src: dict[str, Any], name: str) -> dict[str, Any] | None:
    test = src.get("test")
    if not isinstance(test, list) or test[:1] not in (["CMD"], ["CMD-SHELL"]):
        logger.warning(f"dropping 'healthcheck' from service '{name}': only CMD and CMD-SHELL tests convert")
        return None
    command = test[1:] if test[0] == "CMD" else ["sh", "-c", test[1]]
    probe: dict[str, Any] = {"exec": {"command": command}}
    for key, target in (
        ("start_period", "initialDelaySeconds"),
        ("interval", "periodSeconds"),
        ("timeout", "timeoutSeconds"),
    ):
        if key in src and (seconds := _seconds(src[key])) is not None:
            probe[target] = seconds
    if isinstance(src.get("retries"), int):
        # N retries is a failureThreshold of N+1.
        probe["failureThreshold"] = src["retries"] + 1
    return probe


def _resources(src: dict[str, Any]) -> dict[str, Any]:
    declared = (src.pop("deploy", None) or {}).get("resources") or {}

    def section(block: dict[str, Any]) -> dict[str, Any]:
        out: dict[str, Any] = {}
        if cpus := block.get("cpus"):
            out["cpu"] = cpus
        if memory := block.get("memory"):
            out["memory"] = _quantity(memory)
        return out

    limits = section(declared.get("limits") or {})
    requests = section(declared.get("reservations") or {})
    if mem_limit := src.pop("mem_limit", None):
        limits.setdefault("memory", _quantity(mem_limit))
    if cpus := src.pop("cpus", None):
        limits.setdefault("cpu", cpus)
    resources: dict[str, Any] = {}
    if limits:
        resources["limits"] = limits
        # As the chart's own converter does: requests default to limits for QoS.
        resources["requests"] = {**limits, **requests}
    elif requests:
        resources["requests"] = requests
    return resources


def _security_context(user: Any) -> dict[str, Any]:
    uid, _, gid = str(user).partition(":")
    context: dict[str, Any] = {"runAsUser": int(uid)}
    if gid:
        context["runAsGroup"] = int(gid)
    return context


def _values_service(name: str, service: dict[str, Any], benchmark_image: str | None) -> dict[str, Any]:
    """Convert one compose service to a chart service, dropping what k8s cannot express."""
    src = dict(service)
    out: dict[str, Any] = {}
    build = src.pop("build", None)
    if "image" in src:
        out["image"] = src.pop("image")
    elif build is not None:
        if benchmark_image is None:
            raise ValueError(
                f"service '{name}' is defined by 'build:', which k8s does not support "
                "-- images must be pullable. Pass benchmark_image naming a published image."
            )
        out["image"] = benchmark_image
    if build is not None:
        logger.warning(f"dropping 'build' from service '{name}': k8s images must be pullable")
    # compose entrypoint maps to the chart's command (the container's argv[0]);
    # compose command maps to its args -- unless there is no entrypoint, in which
    # case compose command IS the process to run, so it must be the chart command
    # or the image's own entrypoint runs instead and a `sleep infinity` never fires
    if "entrypoint" in src:
        out["command"] = _as_list(src.pop("entrypoint"))
        if "command" in src:
            out["args"] = _as_list(src.pop("command"))
    elif "command" in src:
        out["command"] = _as_list(src.pop("command"))
    if "working_dir" in src:
        out["workingDir"] = src.pop("working_dir")
    # A DNS record for every service, matching Docker Compose's name resolution.
    out["dnsRecord"] = True
    if "environment" in src:
        out["env"] = _env(src.pop("environment"))
    if "volumes" in src:
        out["volumes"] = src.pop("volumes")
    if "healthcheck" in src:
        if (probe := _readiness_probe(src.pop("healthcheck"), name)) is not None:
            out["readinessProbe"] = probe
    if resources := _resources(src):
        out["resources"] = resources
    if "user" in src:
        out["securityContext"] = _security_context(src.pop("user"))
    if "networks" in src:
        out["networks"] = src.pop("networks")
    # Everything left -- init, privileged, extra_hosts, stop_grace_period, x-default,
    # depends_on, ... -- has no chart equivalent and is dropped rather than passed
    # through to fail schema validation.
    for key in sorted(src):
        logger.warning(f"dropping '{key}' from service '{name}': no k8s equivalent")
    return out


def audit_values(
    task: Task,
    spec: SandboxEnvironmentSpec | None,
    *,
    stage: Path,
    auditor_image: str,
    benchmark_image: str | None = None,
) -> SandboxEnvironmentType:
    """The same audit sandbox as `audit_compose`, emitted as Helm values for k8s.

    On Kubernetes providers (METR's Hawk) the sandbox is a Helm chart, `build:` is
    unsupported, and egress is Cilium deny-by-default. So the auditor's image must be
    published rather than built, and its egress is granted by a per-service network
    policy appended to the values file -- no sandbox-wide `allowDomains`/`allowEntities`
    grants, so the benchmark's services stay as isolated as they were during the eval.

    Args:
        task: The task being audited.
        spec: The sandbox the audited sample runs in, or `None`.
        stage: Directory to write the values file into.
        auditor_image: Published image to run the auditor's service from.
        benchmark_image: Published image standing in for a `build:`-based benchmark
            service. Required if any of their services is built rather than pulled.

    Returns:
        A `("k8s", <values.yaml path>)` sandbox spec.
    """
    values: dict[str, Any] = {}
    converted: dict[str, Any] = {}

    config = spec.config if spec is not None else None
    source = Path(config) if isinstance(config, str) else None
    if source is not None and not is_dockerfile(source.name) and source.is_file():
        compose: dict[str, Any] = yaml.safe_load(source.read_text()) or {}
        theirs: dict[str, Any] = compose.get("services") or {}
        benchmark_name = BENCHMARK_SERVICE
        while benchmark_name in theirs and benchmark_name != "default":
            benchmark_name += "_"
        for name, service in theirs.items():
            converted[benchmark_name if name == "default" else name] = _values_service(
                name, service, benchmark_image
            )
        if volumes := compose.get("volumes"):
            values["volumes"] = {name: {} for name in volumes}
        if networks := compose.get("networks"):
            values["networks"] = {name: {} for name in networks}

    auditor = {"image": auditor_image, "command": ["sleep", "infinity"], "dnsRecord": True}
    values = {"services": {"default": auditor, **converted}, **values}

    stage.mkdir(parents=True, exist_ok=True)
    # Not named `compose.yaml`: the k8s provider reads Helm values, not a compose file.
    out = stage / "values.yaml"
    out.write_text(yaml.safe_dump(values, sort_keys=False) + EGRESS_POLICY)
    return ("k8s", str(out))
