"""The audit sandbox: the audited task's own environment, reproduced.

An auditor needs to read (and sometimes run) the benchmark's real grading code, and
that code routinely lives outside the task's own package. Copying source is fragile
— the import graph fans straight into `inspect_ai` with no clean stopping point — so
the sandbox instead *installs* the distributions that provide the task, pinned to the
versions in the environment the audit is resolved in.
"""

import tempfile
from importlib.metadata import PackageNotFoundError, packages_distributions, version
from pathlib import Path

from inspect_ai import Task
from inspect_ai._eval.task.util import task_run_dir
from inspect_ai.util import SandboxEnvironmentSpec, SandboxEnvironmentType
from inspect_ai.util._sandbox.environment import resolve_sandbox_environment

from ._item import AUDIT_ROOT

__all__ = ["audit_sandbox", "env_files", "resolve_sandbox", "task_requirements"]

DOCKERFILE = """\
# Generated by inspect_audit. The audited task's packages are installed so the
# auditor can read and run the real grading code in place.
FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \\
        git jq ripgrep \\
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir {requirements}

WORKDIR /audit
CMD ["sleep", "infinity"]
"""


def _top_level_modules(task: Task) -> set[str]:
    """Top-level modules implicated in this task: its registry package and scorers."""
    modules: set[str] = set()

    # `inspect_evals/simpleqa_verified` -> `inspect_evals`
    if "/" in task.name:
        modules.add(task.name.split("/")[0])

    scorers = task.scorer if isinstance(task.scorer, list) else [task.scorer]
    for scorer in scorers:
        if scorer is None:
            continue
        fn = getattr(scorer, "__wrapped__", scorer)
        module = getattr(fn, "__module__", "")
        if module:
            modules.add(module.split(".")[0])

    return {m for m in modules if m and m.isidentifier()}


def task_requirements(task: Task) -> list[str]:
    """Pinned pip requirements that provide the audited task.

    Derived from the environment the audit is resolved in, which is the environment
    that could resolve the task in the first place — so it is the closest available
    description of what produced the logs.
    """
    pins: dict[str, str] = {}

    def pin(dist: str) -> None:
        try:
            pins[dist] = version(dist)
        except PackageNotFoundError:
            pass

    pin("inspect-ai")
    distributions = packages_distributions()
    for module in _top_level_modules(task):
        for dist in distributions.get(module, []):
            pin(dist)

    return [f"{dist}=={ver}" for dist, ver in sorted(pins.items())]


def audit_sandbox(task: Task) -> SandboxEnvironmentType:
    """A sandbox for auditing `task`, with the task's own packages installed.

    Writes a generated Dockerfile to a temporary directory and returns a sandbox
    spec pointing at it. Docker layer-caches the build, so the cost is paid once
    per distinct requirement set rather than per audit.
    """
    requirements = task_requirements(task)
    dockerfile = DOCKERFILE.format(requirements=" ".join(requirements))

    out = Path(tempfile.mkdtemp(prefix="inspect_audit_sandbox_")) / "Dockerfile"
    out.write_text(dockerfile)
    return ("docker", str(out))


def resolve_sandbox(task: Task) -> SandboxEnvironmentSpec | None:
    """The audited task's own sandbox, with any relative config path made absolute.

    Inspect resolves a task-level sandbox config relative to the directory the task
    was loaded from, but only for the task it is running. An audit runs its own task
    from its own directory, so a benchmark declaring `("docker", "compose.yaml")`
    would otherwise resolve that name against the audit's working directory.

    Args:
        task: The task being audited.

    Returns:
        The task's sandbox with an absolute config path, or `None` if it declares none.
    """
    spec = resolve_sandbox_environment(task.sandbox)
    if spec is None:
        return None
    if isinstance(spec.config, str) and not Path(spec.config).is_absolute():
        return SandboxEnvironmentSpec(
            spec.type, (Path(task_run_dir(task)) / spec.config).as_posix()
        )
    return spec


def env_files(spec: SandboxEnvironmentType | None, *, stage: Path) -> dict[str, str]:
    """Stage the environment's own definition so an auditor can read how it was built.

    An environment is part of what makes an item solvable or not, so the auditor gets
    the Dockerfile or compose file itself rather than having to infer the environment
    from inside it.

    Args:
        spec: The sandbox the item will run in.
        stage: Directory to stage the definition in.

    Returns:
        Mapping of sandbox path to host path, empty if the sandbox declares no config.
    """
    resolved = resolve_sandbox_environment(spec)
    if resolved is None or resolved.config is None:
        return {}

    stage.mkdir(parents=True, exist_ok=True)
    if isinstance(resolved.config, str):
        source = Path(resolved.config)
        if not source.is_file():
            return {}
        host = stage / source.name
        host.write_bytes(source.read_bytes())
    else:
        # A config object rather than a file (some sandbox providers configure inline).
        host = stage / "sandbox.json"
        host.write_text(resolved.config.model_dump_json(indent=2), encoding="utf-8")

    return {f"{AUDIT_ROOT}/env/{host.name}": str(host)}
